### ISSUE TITLE
ContactCompartment XML code snippet is wrong

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-twedit5#21]
The "ContactCompartment" XML code snippet inserted by Twedit++ is incorrect. It starts with;
`<Plugin Name="Compartment">`

which is incorrect and gives the error
```
INITIALIZING Contact
ERROR: Plugin not registered: Compartment
THIS IS recentErrorMessage=Exception during initialization/parsing :
Plugin not registered: Compartment
Location
FILE :
```
The correct plugin name appears to be
`  <Plugin Name="ContactCompartment">    `

**Comment by maciekswat** [comment]
Fixed
