### ISSUE TITLE
Twedit++ helper for ImpicityMotility plugin inserts code for the volume plugin.

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-twedit5#23]
Windows 11, CC3D 4.3.2

In Twedit++, when you try to insert the ImplicitMotility plugin into the XML you get the volume plugin instead.

If you manually add 
      \<Plugin Name="ImplicitMotility"\/\>
to the .xml no error message is given when run in CC3D, so the plugin is recognized.

**Comment by jpsluka** [comment]
Searched in the Demos and didn't find any examples of ImplicitMotility

**Comment by maciekswat** [comment]
fixed
