### ISSUE TITLE
Duplicate entries of adhesions coefficients

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/cc3d-twedit5#24]
Twedit++ gives the full NxN matrix of adhesions in the XML file. So, adhesions are duplicated:

      <Energy Type1="acell" Type2="bcell">10.0</Energy>

…

     <Energy Type1="bcell" Type2="acell">10.0</Energy>

 

 

      <Energy Type1="Medium" Type2="Medium">10.0</Energy>

      <Energy Type1="Medium" Type2="acell">10.0</Energy>

      <Energy Type1="Medium" Type2="bcell">10.0</Energy>

      <Energy Type1="Medium" Type2="ccell">10.0</Energy>

      <Energy Type1="acell" Type2="Medium">10.0</Energy>

      <Energy Type1="acell" Type2="acell">10.0</Energy>

      <Energy Type1="acell" Type2="bcell">10.0</Energy>

      <Energy Type1="acell" Type2="ccell">10.0</Energy>

      <Energy Type1="bcell" Type2="Medium">10.0</Energy>

     <Energy Type1="bcell" Type2="acell">10.0</Energy>

      <Energy Type1="bcell" Type2="bcell">10.0</Energy>

      <Energy Type1="bcell" Type2="ccell">10.0</Energy>

      <Energy Type1="ccell" Type2="Medium">10.0</Energy>

      <Energy Type1="ccell" Type2="acell">10.0</Energy>

      <Energy Type1="ccell" Type2="bcell">10.0</Energy>

      <Energy Type1="ccell" Type2="ccell">10.0</Energy>

**Comment by maciekswat** [comment]
Fixed, closing the issue
