### ISSUE TITLE
LangthConstraint helper text is incorrect

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-twedit5#28]
In Twedit++(4.4.0) the python inserted for menu item "CC3D Python" - "Cell Constraints" - "Length Constraint by ID" is incorrect.
```
                # Make sure LengthConstraintLocalFlex plugin is loaded
                # Argument Order: cell , lambdaLength, targetLength
                self.lengthConstraintLocalFlexPlugin.setLengthConstraintData(cell, 20, 20)
```

There is no plugin named "LengthConstraintLocalFlex". I believe the inserted text should be:
```
                # Make sure LengthConstraint plugin is loaded
                # Argument Order: cell , lambdaLength, targetLength
                self.lengthConstraint.setLengthConstraintData(cell, 20, 20)
```

**Comment by maciekswat** [comment]
fixed

**Comment by jpsluka** [comment]
The twedit++ helper for the length constraint inserts the wrong code. It inserts:
        self.lengthConstraint.setLengthConstraintData(cell, 20, 20)

But it should be 
       self.lengthConstraintPlugin.setLengthConstraintData(cell, 20, 20)

Twedit++ version 4.6.0 rev 2
